### ISSUE TITLE
Support AVIF

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/photos-app#1269]
AVIF isn't natively supported on mobile, but we could transcode the downloaded image before rendering using [flutter_avif](https://pub.dev/packages/flutter_avif).

This can be processed similar to how we handle HEIF on Android here: https://github.com/ente-io/photos-app/blob/main/lib/utils/file_util.dart#L277-L278

**Comment by mmjsmohit** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by vishnukvmd** [comment]
@mmjsmohit Thanks for offering!

The code has moved since my initial comment. You'll be able to find how we're looking at the file extension and parsing HEIC files separately here: https://github.com/ente-io/photos-app/blob/16db29b886ce9402a853188e2df8d4375ee46bfa/lib/utils/file_util.dart#L240-L246
