### ISSUE TITLE
Thumbnails taking too much time to load on device folder after freeing up space

### ISSUE THREAD

**Issue by ashilkn** [ente-io/photos-app#1292]
**To Reproduce**
1. Backup files from a device folder (I was able to reproduce it for 500 files)
2. Go to device folder on ente and click "Free up space"
3. After space is freed, on opening device folders, the thumbnail's aren't loading.
4. Finally they load after a long time.

**Expected behavior**
Thumbnails load instantly after freeing up space.

**Additional context**
The thumbnails loads right after these logs:
```
I/dependent.debug(23451): Background concurrent copying GC freed 183095(11MB) AllocSpace objects, 32(632KB) LOS objects, 49% free, 13MB/26MB, paused 373us,574us total 107.904ms
I/dependent.debug(23451): Background concurrent copying GC freed 244355(13MB) AllocSpace objects, 10(420KB) LOS objects, 50% free, 16MB/33MB, paused 912us,136us total 103.778ms
I/dependent.debug(23451): Background concurrent copying GC freed 270456(14MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/26MB, paused 185us,164us total 113.677ms
```

Device running on Android version 13

**Comment by ua741** [comment]
Fixed #1406
