### ISSUE TITLE
UI/UX wise the new map button is weird.

### ISSUE THREAD

**Issue by BuzzKnightbeer** [ente-io/photos-app#1315]
Why not put it in the tap bar at the bottom?
Or have a dedicated search tab like Google Photos that can have, for now, the map section. And in the future (hopefully soon) the AI stuff with faces and objects.

**Comment by vishnukvmd** [comment]
This is the layout we'll be moving towards: https://www.figma.com/file/SYtMyLBs5SAOkTbfMMzhqt/ente-Visual-Design?type=design&node-id=11240-62188&mode=design&t=KaxLHw2soVmgUcvJ-4
