### ISSUE TITLE
Provide setting to hide shared items from the home gallery

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/photos-app#1351]
Not everyone might want to see the incoming shared on their home timeline.

ente should provide an option (across all clients) to hide such shared entries from the home screen.

**Comment by creedda** [comment]
Wife is interested in this feature as well.

**Comment by ashilkn** [comment]
This feature is available on Mobile, need to be added to other clients.

**Comment by ashilkn** [comment]
Hey @creedda, after careful consideration, we have decided not to add an option in settings to remove all incoming shared items from the home gallery. Instead, you can just archive the shared albums from inside the album, which will remove items belonging to it from the home gallery.
