### ISSUE TITLE
Edit metadata date in bulk (nice to have)

### ISSUE THREAD

**Issue by ph00lt0** [ente-io/photos-app#1389]
First let me say that I am really enjoying ente and I got convinced of this product in incredible short amount of time.

While uploading a lot of photos in the last days I saw quite many that have incorrect dates in the meta data of old pictures (this is just how I had them). Now because in ente this has more of a use than in my previous solution I wanted to change them but I quickly ran into the work of doing this all one by one. Now given i know the dates of these pictures in one album I would just like to adjust the date of all at once.

**Comment by vishnukvmd** [comment]
Hey, bulk edits for dates are supported in our Desktop app.

Could you please multi-select (holding down the Shift key), and click on the "Fix time" option on the action bar, and let us know if that helps?

Thanks!
