### ISSUE TITLE
Add lightning as payment option for subscription

### ISSUE THREAD

**Issue by jacobburrell** [ente-io/photos-app#1415]
**Feature Request: Integration of Bitcoin Payment via Lightning for Enhanced Privacy**

**Feature Overview:**
Ente stands out from its competitors primarily due to its emphasis on user privacy. To further enhance this privacy-centric approach, introducing a payment option via Bitcoin using the Lightning network would be a significant addition. This would cater to users who prioritize privacy and wish to make electronic payments without disclosing personal details.

**Benefits:**

- Privacy Enhancement: Users can make payments without revealing any personal information.
- Cost Efficiency: By integrating Bitcoin payments, Ente might reduce processing fees, potentially benefiting the customers with reduced costs.
- Diverse Payment Options: While the existing Stripe integration caters to users comfortable with sharing personal details or those with bank accounts/cards, Bitcoin payment would cater to a different user segment.

**Implementation Suggestion:**
- A recommended approach would be to integrate with a self-hosted [BTCPayServer](https://btcpayserver.org/) instance, tailored with Ente branding. BTCPayServer offers a fee-less platform, with the only costs being associated with server maintenance. While there might be fees involved in converting Bitcoin to national currencies, it's plausible to utilize the Bitcoin earnings to offset other operational expenses.

**Conclusion:**
Although Bitcoin payment might seem niche currently, its inclusion would further solidify Ente's commitment to user privacy. Offering diverse payment options not only caters to a broader user base but also reinforces the brand's core values.

**Comment by vishnukvmd** [comment]
Hey @jacobburrell, we already support payments via crypto. We're currently using [BitPay](https://bitpay.com) as our payment provider. These are the currencies they support: [What currencies can I use to pay a BitPay invoice?](https://support.bitpay.com/hc/en-us/articles/203411543-What-currencies-can-I-use-to-pay-a-BitPay-invoice-)

To purchase a subscription with any of the above mentioned currencies, please write to [crypto@ente.io](mailto:crypto@ente.io) from your registered email address, citing the [storage plan](https://ente.io/#pricing) of your choice.
