### ISSUE TITLE
Add Hacktoberfest tag

### ISSUE THREAD

**Issue by mmjsmohit** [ente-io/photos-app#1430]
**Describe your feature**
By adding the Hacktoberfest tag to your repository, you open up an exciting opportunity for developers to contribute and simultaneously enhance their Hacktoberfest profile. This collaboration not only benefits individuals seeking to participate in Hacktoberfest but also adds value to your project by inviting new contributions to help it evolve and improve.

Your repository's inclusion in Hacktoberfest could foster a vibrant community of contributors and provide a platform for skill development, making it a win-win situation for both your project and potential contributors.

**Comment by vishnukvmd** [comment]
Thanks for the suggestion, done! ✅
