### ISSUE TITLE
Filter options

### ISSUE THREAD

**Issue by ThreaT** [ente-io/photos-app#1473]
When viewing content, it would be useful to be able to view only photos or only videos, etc

**Comment by ThreaT** [comment]
Going one step further, it would be awesome if you could add hashtags to individual files so that people can easily find content related to a certain person, activity, location, etc...

**Comment by vishnukvmd** [comment]
Hey, we already support searching by file type ("video", "jpg", ...). Hashtags are already on our roadmap, closing this in favor of the original issue: https://github.com/ente-io/photos-app/issues/1119.

Please reopen if you think I missed something!

**Comment by ThreaT** [comment]
I just wanted to add that hashtags actually make a lot more sense than albums.

Consider this scenario:

- As a user, I would like to share all photos marked with [my-dog] hashtag with my immediate family and I would like to also share the same photos marked with [my-dog] hashtag with some friends but only if those photos were created between 2015-2017.

Using the albums approach:

- The user would have to create two separate albums, one for immediate family and one for friends and then duplicate the photos

Using hashtags approach:

- User can define which users and links have access to which hashtags
- User can define [my-dog] hashtag for immediate family and [my-dog-for-friends] hashtag for friends

So that hashtags also act as a way to handle permissions for each user or group of users.

Furthermore, being able to filter by hashtag in search to see which group of people has visibility to what content would be very user-friendly.

**Comment by ThreaT** [comment]
Here is a simple way to conceptualize how the user-interface can facilitate organizing photos with hashtags in an effective manner

![Screenshot 2023-11-06 170312](https://github.com/ente-io/photos-app/assets/5584548/57bda19b-6b79-4b51-9ab5-a681b827cba7)
