### ISSUE TITLE
Setup of development environment - keeps crashing when I try to login

### ISSUE THREAD

**Issue by cpaulik** [ente-io/photos-app#1480]
**Describe the bug**

Maybe I'm doing this completely wrongly. So sorry if that is the case.

**To Reproduce**
I've followed the instructions on running this in development mode and have the app running on an emulated Pixel 7 running Android13

But when I try to sign into the app inside the emulator I get the following:

```
I/flutter (12802): [Computer][2023-11-07 20:25:34.571967] Started computation for task deriveKey
I/flutter (12802): [Computer][2023-11-07 20:25:34.572944] Found free worker, executing deriveKey on it
Lost connection to device.
```

**Expected behavior**
I'm actually not sure. I guess my questions is: How do I start development / testing if not with my own account?

**Screenshots**

**Comment by ashilkn** [comment]
Could you try increasing the RAM size that can be used by the android emulator? That should make it work. 
Or use a physical device.

**Comment by cpaulik** [comment]
Thanks, that did the trick
