### ISSUE TITLE
Ability to hide system folders from Ente

### ISSUE THREAD

**Issue by heavyelementd** [ente-io/photos-app#1483]
I would like to be able to choose which directories Ente looks for media in on my phone. For example:

I would like to choose:
/DCIM
/Pictures

But would like to not show media in:
/Documents
/Music

This was mentioned on the subreddit here: https://www.reddit.com/r/enteio/comments/17pewe3/

**Comment by vishnukvmd** [comment]
Hey, adding a [NOMEDIA](https://www.lifewire.com/nomedia-file-4172882) should have helped. Could you please let us know how other gallery apps are responding to this?

**Comment by heavyelementd** [comment]
Hi it seems that the file does nothing. I've added it directly to the folder that I want to hide from Ente and neither Ente or Samsung Gallery respects the file.

**Comment by vishnukvmd** [comment]
There are threads on a few different forums where users on Samsung devices are reporting the same issue. I'm not sure we'll be able to help here, since Samsung seems to be breaking Android's contract for media visibility :(

You must have already gotten this right, but just to be sure, could you please verify that the `.nomedia` file is created without an extension?

**Comment by heavyelementd** [comment]
Yes its created exactly as .nomedia, I actually managed to get the app from the article you linked to work for 'non-system' directories just now but will not allow .nomedia in '/Documents' for example, only '/Documents/folder 1'.

I guess this is a limitation to this approach. This has partially worked for me but could I still leave this as a requested feature to have something in the UI to select directories to search within for Media for Ente. 

At the moment its still attempting to upload each album art image I have on my phone from /Music.

**Comment by vishnukvmd** [comment]
Hey, you can configure the app to only upload photos from specific folders.

If you go to Settings > Backup > Backed up folders, you will have an option to unselect `/Music`. Once you do, it will stop uploading items from that folder.

**Comment by heavyelementd** [comment]
Hi sorry its not the uploading of photos I'm trying to get, its attempting to clean up the "On device" section. I've picked the folders I want to backup and its great - I would like, however, to be able to filter the "On device" part to not show each folder containing an album thumbnail.

Realistically I only want Ente to look in /DCIM and /Pictures for new media to suggest to backup (if that makes sense).

I think i've managed to get the functionality using that previously mentioned app by adding the .nomedia files to each folder so thankyou. This might be a very niche and low priority thing. Thanks for your help though.

**Comment by vishnukvmd** [comment]
`.nomedia` was the best way to handle this situation, glad that it's working!

I'll close this issue, if you have any more questions or feedback, feel free to create a new thread on Github / Reddit.
