### ISSUE TITLE
Overall UI seems laggy

### ISSUE THREAD

**Issue by Nithsua** [ente-io/photos-app#1535]
**Describe the bug**
Overall experience is laggy due to occasional frame drops while using the app, especially during page route and scrolling.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.1.1
 - App Version v0.8.1
 

 If there are plans for optimization already in the pipeline. I would be happy to contribute

**Comment by vishnukvmd** [comment]
Hey, looks like there was a regression in our latest release. We'll take a look into this!

**Comment by ua741** [comment]
Hello, 
We have published a new version (v0.8.13) with performance fixes. Please feel free to re-open this issue if you are still facing this issue.
