### ISSUE TITLE
Upload directly to a hidden album

### ISSUE THREAD

**Issue by brog-io** [ente-io/photos-app#1562]
**Describe the feature**
You currently can't upload files directly to hidden. This is annoying since you need to create a separate album and then move them all to hidden.

**Comment by ua741** [comment]
> **Describe the feature** You currently can't upload files directly to hidden. This is annoying since you need to create a separate album and then move them all to hidden.

If you open hidden album, you can directly upload items in that by clicking on add photos icon on the top menu bar.
