### ISSUE TITLE
Dynamic image size in album view

### ISSUE THREAD

**Issue by windmueller** [ente-io/photos-app#1599]
**Describe the feature**
When viewing an album with only a few images for each day, a lot of screen space is wasted:

![Screenshot_20231217-225514](https://github.com/ente-io/photos-app/assets/1096199/c8397a3a-4522-4b67-9617-a92aea5385ac)

In comparison, Google Photos shows 50% more images on the same page while enlarging the preview size dynamically:

![Screenshot_20231217-225557](https://github.com/ente-io/photos-app/assets/1096199/00a2a9bb-bb5e-45dd-955f-bb0262038221)

I know that it is possible to configure the grid size, but this only helps when all albums are shaped equally.

**Comment by vishnukvmd** [comment]
Closing this in favor of #1450

Thanks for the screenshots, have attached them to the original issue :)
