### ISSUE TITLE
Offer smaller radius sizes for custom locations

### ISSUE THREAD

**Issue by windmueller** [ente-io/photos-app#1611]
**Describe the feature**
The definition of custom locations is a unique feature I really like. However, the default lowest radius of 1km is too large. One of the most common locations would be "Home" and here 200m are enough to catch minor glitches of the GPS.

That said, it would be nice if the radius slider would support a lower radius. Adding it manually with "0.2km" already works.

**Comment by ua741** [comment]
Hey,

You can tap on the Radius box and manually set the radius. If this doesn't meet your requirements, please feel free to start a discussion [here](https://github.com/ente-io/ente/discussions/categories/feature-requests).

Thanks!
--
![IMG_6592](https://github.com/ente-io/photos-app/assets/254676/a5eb50e1-7e1c-4868-a4d4-9655f071194f)

![IMG_6594](https://github.com/ente-io/photos-app/assets/254676/b49d4b18-de7b-4dbf-b693-63686b4ad381)
