### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ente-io/photos-app#1633]
https://gitlab.com/linsui/fdroiddata/-/jobs/5858150076 Could you please take a look? Thanks!

**Comment by vishnukvmd** [comment]
Hey @linsui, apologies, this was a merge gone wrong.

Have fixed the issue and pushed [a new tag](https://github.com/ente-io/photos-app/releases/tag/fdroid-v0.8.21).

Thank you for notifying us, and sorry for the troubles!

**Comment by linsui** [comment]
Thanks!
