### ISSUE TITLE
Remove from album hangs forever

### ISSUE THREAD

**Issue by SkypLabs** [ente-io/photos-app#1657]
**Describe the bug**

In some situations, the `Remove from album` action hangs forever.

**To Reproduce**

My personal workflow regarding sorting my photos is as follows:

1. When I take a picture with my phone, it is uploaded and placed into my `Camera` album on Ente.
2. In order to sort my photos, I open the `Camera` album on Ente, select a bunch of items and click on `Add to album` (as of now, it is not possible to use the `Move to album` action with a shared album not owned by ourselves).
3. When asked, I select the album where I want the items to be placed.
4. Once the album selected, it is automatically opened as the current view in the app.
5. I hit the Android return button to go back to the `Camera` album.
6. I select the same items once more.
7. I click on `Remove from album`.
8. The loading animation hangs forever.

As a workaround, I can hit the Android return button once more after step 5 to leave the `Camera` album, renter it, reselect the items and click on `Remove from album` which works this time.

**Expected behavior**

I expect the items to be removed from the `Camera` album from the very first time (step 7).

**Smartphone (please complete the following information):**

 - **Device:** Pixel 8
 - **OS:** GrapheneOS (Android 14)
 - **App Version:** 0.8.21 (F-Droid)

**Comment by ialexpw** [comment]
I've seen this before, occasionally when I mis-tap on the screen and miss the tick for the day it seems to act as if something is selected when no picture/day is selected and if I hit remove it will just endlessly hang in the same way.

**Comment by vishnukvmd** [comment]
Hey, thanks for reporting this, the issue is reproducible. We'll take a look!
