### ISSUE TITLE
Add ability to hide other users photos on the main home page

### ISSUE THREAD

**Issue by vfxninjaeditor** [ente-io/photos-app#1687]
**Describe the feature**
The ability to filter out other family members photos would be very handy. When on the home page shared photos from albums can clutter your feed when trying to find something specific. A filter that allows me to view only my photos would be very nice to have.

**Comment by ashilkn** [comment]
Hey, have you tried archiving the shared album? It will prevent all of the files from that shared album from appearing on the homepage.

**Comment by vfxninjaeditor** [comment]
> Hey, have you tried archiving the shared album and does it work for your use case? It will prevent all of the files from that shared album from appearing on the homepage.

I have not. Does this serve any function other then just hiding the album from view? I'm not looking for a permanent option so much as a toggle when I just want to specifically see my uploads and not 200 from a family member. In the meantime I will use that when I need it.

**Comment by ashilkn** [comment]
> Does this serve any function other then just hiding the album from view
No, archive does exactly that--hides from the home tab gallery.

**Comment by vishnukvmd** [comment]
Closing this, since it sounds like Archive-ing will achieve the desired outcome. Please reopen if you think otherwise!
