### ISSUE TITLE
Support for larger files [4GB+]

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/photos-app#1716]
Currently we have a limit of 4GB per file: https://ente.io/faq/general/file-size-limit/

Removing this would require us to provide resumable uploads and downloads, across all clients, to ensure a decent user experience. Streaming is also a challenge, but not a blocker.

It would make sense to increase the limit from 4GB to something higher, once we have added support for resumption.

**Comment by corsair400r** [comment]
Thank you Vishnukvmd.
 I hope this feature will be soon implemented so I and all others be able to upload larger video files. in my opinion great alternative to Google Photos, a fully encrypted service that I have been looking for so long.

**Comment by MadLittleMods** [comment]
Related discussion https://github.com/ente-io/ente/discussions/583

**Comment by vishnukvmd** [comment]
Hey, we're in the process of migrating all feature requests to discussions, so will close this in favor of https://github.com/ente-io/ente/discussions/583
