### ISSUE TITLE
[Feature] Make it possible to multi select and hide images

### ISSUE THREAD

**Issue by br4yd** [ente-io/photos-app#691]
It’s already possible to hide single items but not possible to hide multiple items at once in the iOS app. This can be very time consuming when wanting to hide several images at once.

**Comment by mnvr** [comment]
This is on the way! Likely we'll not be able to wrap it up by the next release, but I think the release after that will contain this ability to multi-select and hide. Apologies for the wait, my rough estimate is that it'll be around a month before that next-to-next release is out.

**Comment by br4yd** [comment]
Awesome, thank you!

**Comment by mnvr** [comment]
This is now out! In the latest release of the mobile app, you can multi-select and hide.


![IMG_2361 copy](https://user-images.githubusercontent.com/24503581/208452383-017c199e-e709-4854-bbfb-bd27ff3e472e.PNG)
